version: '3'
services:
  postgres:
    image: koldin/postgres_kr:latest
    container_name: postgresql_container
    ports:
      - "1453:5432"
    environment:
      POSTGRES_USER: "wezxro_user"
      POSTGRES_PASSWORD: "testtest"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: "wezxro_master"
      REDIS_PASSWORD: "testtest"

  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: koldin/wezxro_server:latest
    depends_on:
      - redis
      - postgres
    ports:
      - "443:8443"