version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgresql_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "wezxro"
      POSTGRES_USER: "wezxro_user"
      POSTGRES_PASSWORD: "testtest"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: "wezxro_master"
      REDIS_PASSWORD: "testtest"

  app:
    build: .
    image: koldin/wezxro_server:latest
    ports:
      - "8080:8080"