spring:
  mail:
    host: smtp.hostinger.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:1453/wezxro_db
    username: wezxro_user
    password: testtest
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      password: testtest
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
  config:
    activate:
      on-profile: local

server:
  port: 8443
  max-http-request-header-size: 40KB

jwt:
  accessSecret: 'ODZiYzdmYzUtOWJkOC00MWZkLWI2MjktZWJmZTFmODg5YWE5ODZiYzdmYzUtOWJkOC00MWZkLWI2MjktZWJmZTFmODg5YWE5ODZiYzdmYzUtOWJkOC00MWZkLWI2MjktZWJmZTFmODg5YWE5'
  accessExp: 180000
  refreshSecret: 'Y2Y3MTQ1N2EtMWQwYy00MTlhLWE2ODgtZDljMThmNDgyNzQ4ODZiYzdmYzUtOWJkOC00MWZkLWI2MjktZWJmZTFmODg5YWE5ODZiYzdmYzUtOWJkOC00MWZkLWI2MjktZWJmZTFmODg5YWE5'
  refreshExp: 7200

rtpKey: ${RTP_KEY}
secret-key: ${SECRET_KEY}